# Introdução à Numpy

## Numpy 

Pacote básico para computação científica:

-Uma poderosa estrutura de matriz N-dimensional;

-Funções sofisticadas;

-Álgebra linear, transformada de Fourier e recursos de números aleatórios.

NumPy também pode ser usado como um contêiner multidimensional eficiente para dados gerais. 

### Instalação


In [1]:
!pip install numpy


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


### Numpy Arrays

In [2]:
import numpy as np

#### Numpy Arrays vs listas Python

Os arrays NumPy são mais rápidos e compactos do que as listas Python. O NumPy usa muito menos memória para armazenar dados e fornece um mecanismo de especificação dos tipos de dados. Isso permite que o código seja otimizado.

Um array é uma estrutura de dados central da biblioteca NumPy. 

### Inicialização e acesso

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a)
print('---')
print(b)
print('---')
print(b[1])


[1 2 3 4 5 6]
---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
[5 6 7 8]


In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# Uma sequência de de 0 a um valor definido
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
#Com um intervalo definido, primeiro valor é o início, o segundo o fim, o terceiro o incremento

np.arange(3, 30, 2)


array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [7]:
# Especificando o tipo do dado -- o padrão é np.float64

x = np.ones(4, dtype=np.int64)
x

array([1, 1, 1, 1])

## Funções básicas

In [8]:
#Ordenação
arr = np.array([11, 10, 50, 23, 8, 4, 6, 66])

np.sort(arr)

array([ 4,  6,  8, 10, 11, 23, 50, 66])

In [11]:
#Concatenação

a = np.arange(4)
b = np.arange(4,20)

np.concatenate((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
# Concatenação em diferentes dimensões
x = np.array([[1, 2]])
y = np.array([[5, 6]])

result = np.concatenate((x,y), axis=0)
print(result)
print('---')
print(result[0])

[[1 2]
 [5 6]]
---
[1 2]


In [17]:
result = np.concatenate((x,y), axis=1)

print(result)
print('----')
print(result[0])


[[1 2 5 6]]
----
[1 2 5 6]


In [18]:
result.min()

1

In [100]:
result.sum()

14

## Trabalhado com shapes 

In [7]:
# cria um vertor de números aleatórios
array_example = np.random.randn(5)

array_example

array([-1.40023868, -1.76388406,  1.83943164,  0.15896333,  1.6336155 ])

In [9]:
array_example.shape


(5,)

Veja que a saída é esse tipo array de uma dimensão (rank 1 array).
Efeitos talvez indesejados:

In [23]:
#Transposta do vetor criado - não fica transposto
print(array_example.T)
print(array_example.T.shape)

[-0.17826012  0.1889684   1.73799179  2.41066599  0.7099349 ]
(5,)


Ao fazer a transposta estaríamos induzidos a esperar uma multiplicação de matrizes, mas o resultados não é esse.

In [25]:
np.dot(array_example,array_example.T)

9.403419236414148

É recomendado não trabalhar com esse tipo de 'rank 1 array'. 
Garanta que tem linhas e colunas explícitas.

In [11]:
array_example = array_example.reshape((5,1))
print(array_example)


[[-1.40023868]
 [-1.76388406]
 [ 1.83943164]
 [ 0.15896333]
 [ 1.6336155 ]]


In [27]:
print(array_example.T)
print(array_example.T.shape)

[[-0.17826012  0.1889684   1.73799179  2.41066599  0.7099349 ]]
(1, 5)


Agora o np.dot gerará uma multiplicação de matrizes

In [29]:
print(array_example.shape)
np.dot(array_example,array_example.T)

(5, 1)


array([[ 0.03177667, -0.03368553, -0.30981462, -0.4297256 , -0.12655308],
       [-0.03368553,  0.03570905,  0.32842552,  0.45553968,  0.13415526],
       [-0.30981462,  0.32842552,  3.02061545,  4.18971768,  1.23386103],
       [-0.4297256 ,  0.45553968,  4.18971768,  5.81131049,  1.71141592],
       [-0.12655308,  0.13415526,  1.23386103,  1.71141592,  0.50400757]])

In [31]:
# outros usos de reshape

a = np.random.randn(10,1)
print(a.shape)
print('---')
print(a)

(10, 1)
---
[[ 0.22255334]
 [-0.83679511]
 [ 0.86724712]
 [ 0.92034703]
 [-0.79418912]
 [-0.31009306]
 [-0.60933575]
 [ 0.79619884]
 [ 0.57881579]
 [-0.56309219]]


In [32]:
a.reshape((5,2))

array([[ 0.22255334, -0.83679511],
       [ 0.86724712,  0.92034703],
       [-0.79418912, -0.31009306],
       [-0.60933575,  0.79619884],
       [ 0.57881579, -0.56309219]])

In [33]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print('----')
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----
(3, 4)


In [34]:
# Converte para um array 1d

novo = x.flatten()
print(novo)

print(novo.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## Indexação e fatiamento

In [35]:
data = np.array([1, 2, 3, 4, 5])

print(data[1])

print(data[0:2])

print(data[1:])

print(data[-3:])


2
[1 2]
[2 3 4 5]
[3 4 5]


## Operações elementares

In [36]:
a = np.array([1, 2])
b = np.ones(2, dtype=int)

print(a)
print('---')
print(b)
print('---')
print(a+b)

[1 2]
---
[1 1]
---
[2 3]


In [95]:
print(a-b)

[0 1]


In [96]:
print(a*b)

[1 2]


## Broadcasting

Broadcasting é um mecanismo que permite ao NumPy realizar operações em arrays de diferentes formatos. 
As dimensões dos arrays devem ser compatíveis, por exemplo, quando as dimensões de ambos arrays
são iguais ou quando uma delas é 1.

In [37]:
arr = np.array([1.0, 2.0])
arr * 3

array([3., 6.])

Ao operar em dois arrays, o NumPy compara suas formas em termos de elemento. Ele começa com as dimensões finais para as iniciais. Duas dimensões são compatíveis quando

     são iguais, ou

     uma delas é 1

No exemplo anterior

arr =      2   1

Valor 3 =      1

resultado: 2   1

In [16]:
a = np.random.randint(0, 100, size=(3, 2, 1))
print(a)
print('---')
print(a.shape)
print('---')
print(a[0][1][0])


[[[88]
  [13]]

 [[17]
  [ 6]]

 [[32]
  [54]]]
---
(3, 2, 1)
---
13


In [17]:
b = np.random.randint(0, 100, size=(2, 1))

c = a*b

print(c)
print('----')
print(c.shape)

[[[7304]
  [ 819]]

 [[1411]
  [ 378]]

 [[2656]
  [3402]]]
----
(3, 2, 1)


In [14]:
## Quando o broadcasting falha

a = np.random.randint(0, 100, size=(2, 1))
b = np.random.randint(0, 100, size=(5,3, 1))
(a*b).shape


ValueError: operands could not be broadcast together with shapes (2,1) (5,3,1) 